Error fetching data from http://104.248.94.195:8080: HTTPConnectionPool(host='104.248.94.195', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141e530>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://135.181.118.28:8080: HTTPConnectionPool(host='135.181.118.28', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141ecb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://136.243.59.175:8080: HTTPConnectionPool(host='136.243.59.175', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141f400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://142.132.207.31:8080: HTTPConnectionPool(host='142.132.207.31', port=8080): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb21141fb50>, 'Connection to 142.132.207.31 timed out. (connect timeout=5)'))
Error fetching data from http://144.76.104.93:8080: HTTPConnectionPool(host='144.76.104.93', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2111ec2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://5.161.130.81:8080: HTTPConnectionPool(host='5.161.130.81', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://65.108.233.71:8080: HTTPConnectionPool(host='65.108.233.71', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141edd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://88.198.51.250:8080: HTTPConnectionPool(host='88.198.51.250', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb21141e4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://94.130.22.86:8080: HTTPConnectionPool(host='94.130.22.86', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2111ec7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://63.229.234.76:8080': 141722945, 'http://63.229.234.77:8080': 141722945, 'http://65.108.14.25:8080': 141722945}
Nginx configuration updated!
