Error fetching data from http://35.86.200.84:8080/v1: HTTPConnectionPool(host='35.86.200.84', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07d1961ab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://172.104.214.254:8080/v1: HTTPConnectionPool(host='172.104.214.254', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07d1963040>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://192.168.100.42:8080/v1': 380631, 'http://136.244.71.63:8080/v1': 380631, 'http://188.40.107.105:8080/v1': 380631}
Nginx configuration updated!
