Error fetching data from http://84.247.189.19:8080/v1: HTTPConnectionPool(host='84.247.189.19', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59a4b983a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://222.101.31.242:8080/v1': 14187170, 'http://65.109.80.179:8080/v1': 14187170, 'http://172.104.211.8:8080/v1': 14187172, 'http://38.242.137.192:8080/v1': 14187172, 'http://160.202.129.29:8080/v1': 14187172, 'http://209.38.172.53:8080/v1': 14187172, 'http://65.109.30.57:8080/v1': 14187174, 'http://vfn.0l.kalvkusk.io:8080/v1': 14187174, 'http://35.83.165.32:8080/v1': 14187166, 'http://172.86.64.60:8080/v1': 14187180, 'http://202.182.97.107:8080/v1': 14187180, 'http://45.61.132.146:8080/v1': 14187180, 'http://167.88.160.51:8080/v1': 14187180, 'http://37.27.83.253:8080/v1': 14187180, 'http://70.15.242.6:8080/v1': 14187184}
Nginx configuration updated!
