Error fetching data from http://73.181.115.53:8080/v1: HTTPConnectionPool(host='73.181.115.53', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f677df3e8f0>, 'Connection to 73.181.115.53 timed out. (connect timeout=5)'))
Error fetching data from http://136.243.59.175:8080/v1: HTTPConnectionPool(host='136.243.59.175', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f677df3ecb0>, 'Connection to 136.243.59.175 timed out. (connect timeout=5)'))
Error fetching data from http://144.76.104.93:8080/v1: HTTPConnectionPool(host='144.76.104.93', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f677df3f790>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://70.15.242.6:8080/v1': 20319114, 'http://94.130.22.86:8080/v1': 20319162, 'http://104.248.94.195:8080/v1': 20319164}
Nginx configuration updated!
