Error fetching data from http://204.186.74.42:8080/v1: HTTPConnectionPool(host='204.186.74.42', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ca9cba2c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error fetching data from http://51.159.101.31:8080/v1: HTTPConnectionPool(host='51.159.101.31', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ca9cbac50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://65.109.92.57:8080/v1: HTTPConnectionPool(host='65.109.92.57', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ca9cbafe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://65.109.159.23:8080/v1': 151715, 'http://5.9.73.119:8080/v1': 151715, 'http://188.40.107.105:8080/v1': 19944, 'http://212.227.188.13:8080/v1': 151719, 'http://5.161.128.117:8080/v1': 151722, 'http://136.244.71.63:8080/v1': 151722, 'http://136.243.93.42:8080/v1': 151722}
Nginx configuration updated!
