Error fetching data from http://204.186.74.42:8080/v1: HTTPConnectionPool(host='204.186.74.42', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a1b8368f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error fetching data from http://65.108.73.53:8080/v1: HTTPConnectionPool(host='65.108.73.53', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0a1b836b30>, 'Connection to 65.108.73.53 timed out. (connect timeout=5)'))
Error fetching data from http://188.40.107.105:8080/v1: HTTPConnectionPool(host='188.40.107.105', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a1b8377c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://206.168.191.223:8080/v1': 1336384, 'http://65.109.159.23:8080/v1': 1336398, 'http://136.244.71.63:8080/v1': 1336400, 'http://65.109.92.57:8080/v1': 1336400, 'http://5.9.73.119:8080/v1': 1336402, 'http://65.109.80.179:8080/v1': 1336404, 'http://66.94.98.20:8080/v1': 1336404, 'http://136.243.93.42:8080/v1': 1336404, 'http://35.86.200.84:8080/v1': 1336406, 'http://5.161.128.117:8080/v1': 1336406}
Nginx configuration updated!
